<?php

namespace App\Http\Controllers;

// use App\Models\User;
// use Illuminate\Http\RedirectResponse;
// use Illuminate\Http\Request;
// use Illuminate\Support\Str;
use Laravel\Socialite\Facades\Socialite;


class GoogleLoginController extends Controller
{
    //
    // public function redirectToGoogle(): RedirectResponse
    // {
    //     return Socialite::driver('google')->redirect();
    // }


    public function handleGoogleCallback()
    {
        
        // $user = Socialite::driver('google')->user();
        $user = Socialite::driver('google')->user();


        // Redirect to url as requested by user, if empty use /dashboard page as generated by Jetstream
        return redirect("/");
    }
}
